version: '3'

services:
  nodeserv:
    tty: true
    build:
      context: ./minimal-nodeserv
      dockerfile: Dockerfile
    image: synerex_nodeserv
    entrypoint: ["/sxbin/nodeserv","-addr","0.0.0.0"]
    ports:
      - "9990:9990"
    networks: 
      - synerex-network
  sxserver:
    tty: true
    build:
      context: ./minimal-sxserver
      dockerfile: Dockerfile
    image: synerex_server
    environment:
      - SX_SERVER_HOST=sxserver
      - SX_NODESERV_HOST=nodeserv
    depends_on:
      - "nodeserv"
    ports:
      - "10000:10000"
    networks: 
      - synerex-network
networks:
  synerex-network:
    external: true
